version: "3.1"

services:
  db:
    image: postgres:15
    restart: always
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    ports:
      - 5400:5432
    environment:
      POSTGRES_PASSWORD: postgres
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./data/rb:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
